/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package comis.views;

import com.rameses.osiris2.themes.FormPage;
import com.rameses.rcp.ui.annotations.StyleSheet;
import com.rameses.rcp.ui.annotations.Template;

@Template(FormPage.class)
@StyleSheet()
public class DeceasedListReportInitPage extends javax.swing.JPanel {

    /**
     * Creates new form ExpiredLeaseContractInitReportPage
     */
    public DeceasedListReportInitPage() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        xFormPanel1 = new com.rameses.rcp.control.XFormPanel();
        xComboBox1 = new com.rameses.rcp.control.XComboBox();
        xIntegerField1 = new com.rameses.rcp.control.XIntegerField();
        xComboBox4 = new com.rameses.rcp.control.XComboBox();
        xComboBox5 = new com.rameses.rcp.control.XComboBox();
        xComboBox6 = new com.rameses.rcp.control.XComboBox();
        xFormPanel2 = new com.rameses.rcp.control.XFormPanel();
        xIntegerField4 = new com.rameses.rcp.control.XIntegerField();
        xComboBox7 = new com.rameses.rcp.control.XComboBox();
        xFormPanel3 = new com.rameses.rcp.control.XFormPanel();
        xIntegerField5 = new com.rameses.rcp.control.XIntegerField();
        xComboBox8 = new com.rameses.rcp.control.XComboBox();
        xComboBox9 = new com.rameses.rcp.control.XComboBox();

        xFormPanel1.setCaptionWidth(100);

        xComboBox1.setCaption("Period");
        xComboBox1.setItems("periods");
        xComboBox1.setName("query.period"); // NOI18N
        xComboBox1.setEmptyText("ALL");
        xComboBox1.setPreferredSize(new java.awt.Dimension(130, 20));
        xFormPanel1.add(xComboBox1);

        xIntegerField1.setCaption("Year");
        xIntegerField1.setDepends(new String[] {"query.period"});
        xIntegerField1.setName("query.year"); // NOI18N
        xIntegerField1.setPreferredSize(new java.awt.Dimension(130, 20));
        xFormPanel1.add(xIntegerField1);

        xComboBox4.setCaption("Quarter");
        xComboBox4.setDepends(new String[] {"query.period"});
        xComboBox4.setItems("quarters");
        xComboBox4.setName("query.qtr"); // NOI18N
        xComboBox4.setAllowNull(false);
        xComboBox4.setEmptyText("ALL");
        xComboBox4.setPreferredSize(new java.awt.Dimension(130, 20));
        xFormPanel1.add(xComboBox4);

        xComboBox5.setCaption("Month");
        xComboBox5.setDepends(new String[] {"query.period"});
        xComboBox5.setExpression("#{item.caption}");
        xComboBox5.setItems("months");
        xComboBox5.setName("query.month"); // NOI18N
        xComboBox5.setAllowNull(false);
        xComboBox5.setEmptyText("ALL");
        xComboBox5.setPreferredSize(new java.awt.Dimension(130, 20));
        xFormPanel1.add(xComboBox5);

        xComboBox6.setCaption("Age Group");
        xComboBox6.setExpression("#{item.caption}");
        xComboBox6.setItems("agegroups");
        xComboBox6.setName("query.agegroup"); // NOI18N
        xComboBox6.setEmptyText("ALL");
        xComboBox6.setPreferredSize(new java.awt.Dimension(200, 20));
        xFormPanel1.add(xComboBox6);

        xFormPanel2.setCaptionBorder(null);
        xFormPanel2.setOrientation(com.rameses.rcp.constant.UIConstants.HORIZONTAL);
        xFormPanel2.setPadding(new java.awt.Insets(0, 0, 0, 0));
        xFormPanel2.setShowCaption(false);

        xIntegerField4.setCaption("Age From");
        xIntegerField4.setDepends(new String[] {"query.agegroup"});
        xIntegerField4.setName("query.agefrom"); // NOI18N
        xIntegerField4.setCaptionWidth(100);
        xIntegerField4.setPreferredSize(new java.awt.Dimension(70, 20));
        xFormPanel2.add(xIntegerField4);

        xComboBox7.setDepends(new String[] {"query.agegroup"});
        xComboBox7.setItems("agetypes");
        xComboBox7.setName("query.agefromtype"); // NOI18N
        xComboBox7.setAllowNull(false);
        xComboBox7.setPreferredSize(new java.awt.Dimension(128, 20));
        xComboBox7.setShowCaption(false);
        xFormPanel2.add(xComboBox7);

        xFormPanel1.add(xFormPanel2);

        xFormPanel3.setCaptionBorder(null);
        xFormPanel3.setOrientation(com.rameses.rcp.constant.UIConstants.HORIZONTAL);
        xFormPanel3.setPadding(new java.awt.Insets(0, 0, 0, 0));
        xFormPanel3.setShowCaption(false);

        xIntegerField5.setCaption("Age To");
        xIntegerField5.setDepends(new String[] {"query.agegroup"});
        xIntegerField5.setName("query.ageto"); // NOI18N
        xIntegerField5.setCaptionWidth(100);
        xIntegerField5.setPreferredSize(new java.awt.Dimension(70, 20));
        xFormPanel3.add(xIntegerField5);

        xComboBox8.setDepends(new String[] {"query.agegroup"});
        xComboBox8.setItems("agetypes");
        xComboBox8.setName("query.agetotype"); // NOI18N
        xComboBox8.setAllowNull(false);
        xComboBox8.setPreferredSize(new java.awt.Dimension(128, 20));
        xComboBox8.setShowCaption(false);
        xFormPanel3.add(xComboBox8);

        xFormPanel1.add(xFormPanel3);

        xComboBox9.setCaption("LGU");
        xComboBox9.setExpression("#{item.objid}");
        xComboBox9.setItems("lgus");
        xComboBox9.setName("query.lgu"); // NOI18N
        xComboBox9.setEmptyText("ALL");
        xComboBox9.setPreferredSize(new java.awt.Dimension(200, 20));
        xFormPanel1.add(xComboBox9);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(xFormPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 420, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(49, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(xFormPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 229, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private com.rameses.rcp.control.XComboBox xComboBox1;
    private com.rameses.rcp.control.XComboBox xComboBox4;
    private com.rameses.rcp.control.XComboBox xComboBox5;
    private com.rameses.rcp.control.XComboBox xComboBox6;
    private com.rameses.rcp.control.XComboBox xComboBox7;
    private com.rameses.rcp.control.XComboBox xComboBox8;
    private com.rameses.rcp.control.XComboBox xComboBox9;
    private com.rameses.rcp.control.XFormPanel xFormPanel1;
    private com.rameses.rcp.control.XFormPanel xFormPanel2;
    private com.rameses.rcp.control.XFormPanel xFormPanel3;
    private com.rameses.rcp.control.XIntegerField xIntegerField1;
    private com.rameses.rcp.control.XIntegerField xIntegerField4;
    private com.rameses.rcp.control.XIntegerField xIntegerField5;
    // End of variables declaration//GEN-END:variables
}
