/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package comis.views;

import com.rameses.osiris2.themes.FormPage;
import com.rameses.rcp.ui.annotations.StyleSheet;
import com.rameses.rcp.ui.annotations.Template;

@Template(FormPage.class)
@StyleSheet()
public class PeriodFilterInitPage extends javax.swing.JPanel {

    /**
     * Creates new form ExpiredLeaseContractInitReportPage
     */
    public PeriodFilterInitPage() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        xFormPanel1 = new com.rameses.rcp.control.XFormPanel();
        xComboBox1 = new com.rameses.rcp.control.XComboBox();
        xIntegerField1 = new com.rameses.rcp.control.XIntegerField();
        xComboBox4 = new com.rameses.rcp.control.XComboBox();
        xComboBox5 = new com.rameses.rcp.control.XComboBox();

        xFormPanel1.setCaptionWidth(100);

        xComboBox1.setCaption("Period");
        xComboBox1.setItems("periods");
        xComboBox1.setName("query.period"); // NOI18N
        xComboBox1.setEmptyText("ALL");
        xComboBox1.setPreferredSize(new java.awt.Dimension(130, 20));
        xFormPanel1.add(xComboBox1);

        xIntegerField1.setCaption("Year");
        xIntegerField1.setDepends(new String[] {"query.period"});
        xIntegerField1.setName("query.year"); // NOI18N
        xIntegerField1.setPreferredSize(new java.awt.Dimension(130, 20));
        xFormPanel1.add(xIntegerField1);

        xComboBox4.setCaption("Quarter");
        xComboBox4.setDepends(new String[] {"query.period"});
        xComboBox4.setItems("quarters");
        xComboBox4.setName("query.qtr"); // NOI18N
        xComboBox4.setAllowNull(false);
        xComboBox4.setEmptyText("ALL");
        xComboBox4.setPreferredSize(new java.awt.Dimension(130, 20));
        xFormPanel1.add(xComboBox4);

        xComboBox5.setCaption("Month");
        xComboBox5.setDepends(new String[] {"query.period"});
        xComboBox5.setExpression("#{item.caption}");
        xComboBox5.setItems("months");
        xComboBox5.setName("query.month"); // NOI18N
        xComboBox5.setAllowNull(false);
        xComboBox5.setEmptyText("ALL");
        xComboBox5.setPreferredSize(new java.awt.Dimension(130, 20));
        xFormPanel1.add(xComboBox5);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(xFormPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 420, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(49, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(xFormPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 229, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private com.rameses.rcp.control.XComboBox xComboBox1;
    private com.rameses.rcp.control.XComboBox xComboBox4;
    private com.rameses.rcp.control.XComboBox xComboBox5;
    private com.rameses.rcp.control.XFormPanel xFormPanel1;
    private com.rameses.rcp.control.XIntegerField xIntegerField1;
    // End of variables declaration//GEN-END:variables
}
