/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package comis.views;

import com.rameses.rcp.ui.annotations.StyleSheet;
import com.rameses.rcp.ui.annotations.Template;
import com.rameses.seti2.views.CrudFormPage;

@Template(CrudFormPage.class)
@StyleSheet()
public class ApplicationPage extends javax.swing.JPanel {

    /**
     * Creates new form ResourcePage
     */
    public ApplicationPage() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        xFormPanel1 = new com.rameses.rcp.control.XFormPanel();
        xLabel1 = new com.rameses.rcp.control.XLabel();
        xComboBox1 = new com.rameses.rcp.control.XComboBox();
        xTextField1 = new com.rameses.rcp.control.XTextField();
        xIntegerField1 = new com.rameses.rcp.control.XIntegerField();
        xDateField1 = new com.rameses.rcp.control.XDateField();
        xDateField2 = new com.rameses.rcp.control.XDateField();
        xDateField3 = new com.rameses.rcp.control.XDateField();
        xLookupField2 = new com.rameses.rcp.control.XLookupField();
        xLabel10 = new com.rameses.rcp.control.XLabel();
        xComboBox2 = new com.rameses.rcp.control.XComboBox();
        xFormPanel2 = new com.rameses.rcp.control.XFormPanel();
        xButton1 = new com.rameses.rcp.control.XButton();
        xLabel7 = new com.rameses.rcp.control.XLabel();
        xLabel2 = new com.rameses.rcp.control.XLabel();
        xLabel3 = new com.rameses.rcp.control.XLabel();
        xLabel4 = new com.rameses.rcp.control.XLabel();
        xLabel5 = new com.rameses.rcp.control.XLabel();
        xLabel6 = new com.rameses.rcp.control.XLabel();
        xLookupField1 = new com.rameses.rcp.control.XLookupField();
        xLabel8 = new com.rameses.rcp.control.XLabel();
        xLabel9 = new com.rameses.rcp.control.XLabel();

        xFormPanel1.setCaptionWidth(120);

        xLabel1.setCaption("State");
        xLabel1.setExpression("#{entity.state}");
        xLabel1.setCellPadding(new java.awt.Insets(0, 0, 10, 0));
        xLabel1.setPreferredSize(new java.awt.Dimension(0, 19));
        xFormPanel1.add(xLabel1);

        xComboBox1.setCaption("App Type");
        xComboBox1.setItems("apptypes");
        xComboBox1.setName("entity.apptype"); // NOI18N
        xComboBox1.setPreferredSize(new java.awt.Dimension(100, 20));
        xComboBox1.setRequired(true);
        xFormPanel1.add(xComboBox1);

        xTextField1.setCaption("App No.");
        xTextField1.setName("entity.appno"); // NOI18N
        xFormPanel1.add(xTextField1);

        xIntegerField1.setCaption("App Year");
        xIntegerField1.setName("entity.appyear"); // NOI18N
        xIntegerField1.setRequired(true);
        xFormPanel1.add(xIntegerField1);

        xDateField1.setCaption("Date Applied");
        xDateField1.setName("entity.dtapplied"); // NOI18N
        xDateField1.setRequired(true);
        xFormPanel1.add(xDateField1);

        xDateField2.setCaption("Date Approved");
        xDateField2.setName("entity.dtapproved"); // NOI18N
        xDateField2.setRequired(true);
        xFormPanel1.add(xDateField2);

        xDateField3.setCaption("Expiry Date");
        xDateField3.setName("entity.dtexpiry"); // NOI18N
        xDateField3.setCellPadding(new java.awt.Insets(0, 0, 10, 0));
        xDateField3.setRequired(true);
        xFormPanel1.add(xDateField3);

        xLookupField2.setCaption("Applicant");
        xLookupField2.setExpression("#{item.name}");
        xLookupField2.setHandler("lookupApplicant");
        xLookupField2.setName("entity.applicant"); // NOI18N
        xLookupField2.setPreferredSize(new java.awt.Dimension(0, 20));
        xLookupField2.setRequired(true);
        xFormPanel1.add(xLookupField2);

        xLabel10.setCaption("Address");
        xLabel10.setDepends(new String[] {"entity.applicant"});
        xLabel10.setExpression("#{entity.applicant.address}");
        xLabel10.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 153, 153)));
        xLabel10.setPreferredSize(new java.awt.Dimension(0, 19));
        xFormPanel1.add(xLabel10);

        xComboBox2.setCaption("Relationship");
        xComboBox2.setDepends(new String[] {"entity.applicant"});
        xComboBox2.setExpression("#{item.title}");
        xComboBox2.setItems("relations");
        xComboBox2.setName("entity.relation"); // NOI18N
        xComboBox2.setCellPadding(new java.awt.Insets(0, 0, 10, 0));
        xComboBox2.setPreferredSize(new java.awt.Dimension(0, 20));
        xComboBox2.setRequired(true);
        xFormPanel1.add(xComboBox2);

        xFormPanel2.setOrientation(com.rameses.rcp.constant.UIConstants.HORIZONTAL);
        xFormPanel2.setPadding(new java.awt.Insets(0, 0, 0, 0));
        xFormPanel2.setShowCaption(false);
        xFormPanel2.setStretchWidth(100);

        xButton1.setName("openDeceased"); // NOI18N
        xButton1.setImmediate(true);
        xButton1.setPreferredSize(new java.awt.Dimension(118, 23));
        xButton1.setShowCaption(false);
        xButton1.setText("Deceased Person");
        xFormPanel2.add(xButton1);

        xLabel7.setCaption("Nationality");
        xLabel7.setDepends(new String[] {"entity.deceased"});
        xLabel7.setExpression("#{entity.deceased.name}");
        xLabel7.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 153, 153)));
        xLabel7.setPreferredSize(new java.awt.Dimension(0, 21));
        xLabel7.setShowCaption(false);
        xFormPanel2.add(xLabel7);

        xFormPanel1.add(xFormPanel2);

        xLabel2.setCaption("Nationality");
        xLabel2.setDepends(new String[] {"entity.deceased"});
        xLabel2.setExpression("#{entity.deceased.nationality}");
        xLabel2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 153, 153)));
        xLabel2.setPreferredSize(new java.awt.Dimension(0, 19));
        xFormPanel1.add(xLabel2);

        xLabel3.setCaption("Age");
        xLabel3.setDepends(new String[] {"entity.deceased"});
        xLabel3.setExpression("#{entity.deceased.age}");
        xLabel3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 153, 153)));
        xLabel3.setPreferredSize(new java.awt.Dimension(0, 19));
        xFormPanel1.add(xLabel3);

        xLabel4.setCaption("Sex");
        xLabel4.setDepends(new String[] {"entity.deceased"});
        xLabel4.setExpression("#{entity.deceased.sex}");
        xLabel4.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 153, 153)));
        xLabel4.setPreferredSize(new java.awt.Dimension(0, 19));
        xFormPanel1.add(xLabel4);

        xLabel5.setCaption("Date of Death");
        xLabel5.setDepends(new String[] {"entity.deceased"});
        xLabel5.setExpression("#{entity.deceased.dtdied}");
        xLabel5.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 153, 153)));
        xLabel5.setPreferredSize(new java.awt.Dimension(0, 19));
        xFormPanel1.add(xLabel5);

        xLabel6.setCaption("Cause of Death");
        xLabel6.setDepends(new String[] {"entity.deceased"});
        xLabel6.setExpression("#{entity.deceased.causeofdeath.title}");
        xLabel6.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 153, 153)));
        xLabel6.setCellPadding(new java.awt.Insets(0, 0, 10, 0));
        xLabel6.setPreferredSize(new java.awt.Dimension(0, 19));
        xFormPanel1.add(xLabel6);

        xLookupField1.setCaption("Resource");
        xLookupField1.setExpression("#{item.name}");
        xLookupField1.setHandler("cemetery_resource:lookup");
        xLookupField1.setName("entity.resourceinfo"); // NOI18N
        xLookupField1.setPreferredSize(new java.awt.Dimension(0, 20));
        xLookupField1.setRequired(true);
        xFormPanel1.add(xLookupField1);

        xLabel8.setCaption("Resource Type");
        xLabel8.setDepends(new String[] {"entity.resourceinfo"});
        xLabel8.setExpression("#{entity.resourceinfo.resource.name}");
        xLabel8.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 153, 153)));
        xLabel8.setPreferredSize(new java.awt.Dimension(0, 19));
        xFormPanel1.add(xLabel8);

        xLabel9.setCaption("Area (sqm)");
        xLabel9.setDepends(new String[] {"entity.resourceinfo"});
        xLabel9.setExpression("#{entity.resourceinfo.areasqm}");
        xLabel9.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 153, 153)));
        xLabel9.setPreferredSize(new java.awt.Dimension(0, 19));
        xFormPanel1.add(xLabel9);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(xFormPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 449, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(149, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(xFormPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 520, Short.MAX_VALUE)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private com.rameses.rcp.control.XButton xButton1;
    private com.rameses.rcp.control.XComboBox xComboBox1;
    private com.rameses.rcp.control.XComboBox xComboBox2;
    private com.rameses.rcp.control.XDateField xDateField1;
    private com.rameses.rcp.control.XDateField xDateField2;
    private com.rameses.rcp.control.XDateField xDateField3;
    private com.rameses.rcp.control.XFormPanel xFormPanel1;
    private com.rameses.rcp.control.XFormPanel xFormPanel2;
    private com.rameses.rcp.control.XIntegerField xIntegerField1;
    private com.rameses.rcp.control.XLabel xLabel1;
    private com.rameses.rcp.control.XLabel xLabel10;
    private com.rameses.rcp.control.XLabel xLabel2;
    private com.rameses.rcp.control.XLabel xLabel3;
    private com.rameses.rcp.control.XLabel xLabel4;
    private com.rameses.rcp.control.XLabel xLabel5;
    private com.rameses.rcp.control.XLabel xLabel6;
    private com.rameses.rcp.control.XLabel xLabel7;
    private com.rameses.rcp.control.XLabel xLabel8;
    private com.rameses.rcp.control.XLabel xLabel9;
    private com.rameses.rcp.control.XLookupField xLookupField1;
    private com.rameses.rcp.control.XLookupField xLookupField2;
    private com.rameses.rcp.control.XTextField xTextField1;
    // End of variables declaration//GEN-END:variables
}
