/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package comis.views;

import com.rameses.osiris2.themes.FormPage;
import com.rameses.rcp.ui.annotations.Template;

@Template(FormPage.class)
public class ApplicationTransferInitPage extends javax.swing.JPanel {

    /**
     * Creates new form ApplicationRenewalInitPage
     */
    public ApplicationTransferInitPage() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        xFormPanel1 = new com.rameses.rcp.control.XFormPanel();
        xLookupField2 = new com.rameses.rcp.control.XLookupField();
        xLookupField3 = new com.rameses.rcp.control.XLookupField();
        xLabel7 = new com.rameses.rcp.control.XLabel();
        xLabel4 = new com.rameses.rcp.control.XLabel();
        xLabel6 = new com.rameses.rcp.control.XLabel();
        xLabel5 = new com.rameses.rcp.control.XLabel();
        xLabel9 = new com.rameses.rcp.control.XLabel();
        xLabel10 = new com.rameses.rcp.control.XLabel();
        xLabel11 = new com.rameses.rcp.control.XLabel();
        xLabel12 = new com.rameses.rcp.control.XLabel();
        xLabel13 = new com.rameses.rcp.control.XLabel();
        xLabel14 = new com.rameses.rcp.control.XLabel();
        xLabel15 = new com.rameses.rcp.control.XLabel();

        xFormPanel1.setCaptionWidth(120);
        xFormPanel1.setPreferredSize(new java.awt.Dimension(0, 100));

        xLookupField2.setCaption("Application No.");
        xLookupField2.setExpression("#{item.appno}");
        xLookupField2.setHandler("lookupApplication");
        xLookupField2.setName("entity.prevapp"); // NOI18N
        xLookupField2.setPreferredSize(new java.awt.Dimension(0, 20));
        xLookupField2.setRequired(true);
        xFormPanel1.add(xLookupField2);

        xLookupField3.setCaption("Transfer to");
        xLookupField3.setExpression("#{item.name} (Section ${item.section.code}  Block ${item.block.code})");
        xLookupField3.setHandler("lookupResourceInfo");
        xLookupField3.setName("entity.resourceinfo"); // NOI18N
        xLookupField3.setPreferredSize(new java.awt.Dimension(0, 20));
        xLookupField3.setRequired(true);
        xFormPanel1.add(xLookupField3);

        xLabel7.setDepends(new String[] {"entity.prevapp"});
        xLabel7.setExpression("#{\"DECEASED\"}");
        xLabel7.setVisibleWhen("#{entity.prevapp != null}");
        xLabel7.setCellPadding(new java.awt.Insets(10, 0, 0, 0));
        xLabel7.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        xLabel7.setPreferredSize(new java.awt.Dimension(0, 19));
        xLabel7.setShowCaption(false);
        xFormPanel1.add(xLabel7);

        xLabel4.setCaption("Name");
        xLabel4.setDepends(new String[] {"entity.prevapp"});
        xLabel4.setExpression("#{entity.prevapp.deceased.name}");
        xLabel4.setVisibleWhen("#{entity.prevapp != null}");
        xLabel4.setCellPadding(new java.awt.Insets(0, 30, 0, 0));
        xLabel4.setPreferredSize(new java.awt.Dimension(0, 19));
        xFormPanel1.add(xLabel4);

        xLabel6.setCaption("Nationality");
        xLabel6.setDepends(new String[] {"entity.prevapp"});
        xLabel6.setExpression("#{entity.prevapp.deceased.nationality}");
        xLabel6.setVisibleWhen("#{entity.prevapp != null}");
        xLabel6.setCellPadding(new java.awt.Insets(0, 30, 0, 0));
        xLabel6.setPreferredSize(new java.awt.Dimension(0, 19));
        xFormPanel1.add(xLabel6);

        xLabel5.setCaption("Age");
        xLabel5.setDepends(new String[] {"entity.prevapp"});
        xLabel5.setExpression("#{entity.prevapp.deceased.age}");
        xLabel5.setVisibleWhen("#{entity.prevapp != null}");
        xLabel5.setCellPadding(new java.awt.Insets(0, 30, 0, 0));
        xLabel5.setPreferredSize(new java.awt.Dimension(0, 19));
        xFormPanel1.add(xLabel5);

        xLabel9.setCaption("Sex");
        xLabel9.setDepends(new String[] {"entity.prevapp"});
        xLabel9.setExpression("#{entity.prevapp.deceased.sex}");
        xLabel9.setVisibleWhen("#{entity.prevapp != null}");
        xLabel9.setCellPadding(new java.awt.Insets(0, 30, 0, 0));
        xLabel9.setPreferredSize(new java.awt.Dimension(0, 19));
        xFormPanel1.add(xLabel9);

        xLabel10.setDepends(new String[] {"entity.prevapp"});
        xLabel10.setExpression("#{\"RESOURCE\"}");
        xLabel10.setVisibleWhen("#{entity.prevapp != null}");
        xLabel10.setCellPadding(new java.awt.Insets(10, 0, 0, 0));
        xLabel10.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        xLabel10.setPreferredSize(new java.awt.Dimension(0, 19));
        xLabel10.setShowCaption(false);
        xFormPanel1.add(xLabel10);

        xLabel11.setCaption("Code");
        xLabel11.setDepends(new String[] {"entity.prevapp"});
        xLabel11.setExpression("#{entity.prevapp.resourceinfo.code}");
        xLabel11.setVisibleWhen("#{entity.prevapp != null}");
        xLabel11.setCellPadding(new java.awt.Insets(0, 30, 0, 0));
        xLabel11.setPreferredSize(new java.awt.Dimension(0, 19));
        xFormPanel1.add(xLabel11);

        xLabel12.setCaption("Name");
        xLabel12.setDepends(new String[] {"entity.prevapp"});
        xLabel12.setExpression("#{entity.prevapp.resourceinfo.name}");
        xLabel12.setVisibleWhen("#{entity.prevapp != null}");
        xLabel12.setCellPadding(new java.awt.Insets(0, 30, 0, 0));
        xLabel12.setPreferredSize(new java.awt.Dimension(0, 19));
        xFormPanel1.add(xLabel12);

        xLabel13.setCaption("Area (sqm)");
        xLabel13.setDepends(new String[] {"entity.prevapp"});
        xLabel13.setExpression("#{entity.prevapp.resourceinfo.areasqm}");
        xLabel13.setVisibleWhen("#{entity.prevapp != null}");
        xLabel13.setCellPadding(new java.awt.Insets(0, 30, 0, 0));
        xLabel13.setPreferredSize(new java.awt.Dimension(0, 19));
        xFormPanel1.add(xLabel13);

        xLabel14.setCaption("Width");
        xLabel14.setDepends(new String[] {"entity.prevapp"});
        xLabel14.setExpression("#{entity.prevapp.resourceinfo.width}");
        xLabel14.setVisibleWhen("#{entity.prevapp != null}");
        xLabel14.setCellPadding(new java.awt.Insets(0, 30, 0, 0));
        xLabel14.setPreferredSize(new java.awt.Dimension(0, 19));
        xFormPanel1.add(xLabel14);

        xLabel15.setCaption("Length");
        xLabel15.setDepends(new String[] {"entity.prevapp"});
        xLabel15.setExpression("#{entity.prevapp.resourceinfo.length}");
        xLabel15.setVisibleWhen("#{entity.prevapp != null}");
        xLabel15.setCellPadding(new java.awt.Insets(0, 30, 0, 0));
        xLabel15.setPreferredSize(new java.awt.Dimension(0, 19));
        xFormPanel1.add(xLabel15);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(xFormPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 455, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(48, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(xFormPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 320, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(49, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private com.rameses.rcp.control.XFormPanel xFormPanel1;
    private com.rameses.rcp.control.XLabel xLabel10;
    private com.rameses.rcp.control.XLabel xLabel11;
    private com.rameses.rcp.control.XLabel xLabel12;
    private com.rameses.rcp.control.XLabel xLabel13;
    private com.rameses.rcp.control.XLabel xLabel14;
    private com.rameses.rcp.control.XLabel xLabel15;
    private com.rameses.rcp.control.XLabel xLabel4;
    private com.rameses.rcp.control.XLabel xLabel5;
    private com.rameses.rcp.control.XLabel xLabel6;
    private com.rameses.rcp.control.XLabel xLabel7;
    private com.rameses.rcp.control.XLabel xLabel9;
    private com.rameses.rcp.control.XLookupField xLookupField2;
    private com.rameses.rcp.control.XLookupField xLookupField3;
    // End of variables declaration//GEN-END:variables
}
