/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package comis.views;

import com.rameses.rcp.ui.annotations.StyleSheet;
import com.rameses.rcp.ui.annotations.Template;
import com.rameses.seti2.views.CrudFormPage;

@Template(CrudFormPage.class)
@StyleSheet()
public class ApplicationPage extends javax.swing.JPanel {

    /**
     * Creates new form ResourcePage
     */
    public ApplicationPage() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel2 = new javax.swing.JPanel();
        xFormPanel1 = new com.rameses.rcp.control.XFormPanel();
        xLabel1 = new com.rameses.rcp.control.XLabel();
        xComboBox1 = new com.rameses.rcp.control.XComboBox();
        xTextField1 = new com.rameses.rcp.control.XTextField();
        xIntegerField1 = new com.rameses.rcp.control.XIntegerField();
        xDateField1 = new com.rameses.rcp.control.XDateField();
        xDateField2 = new com.rameses.rcp.control.XDateField();
        xDateField3 = new com.rameses.rcp.control.XDateField();
        xLookupField2 = new com.rameses.rcp.control.XLookupField();
        xLabel10 = new com.rameses.rcp.control.XLabel();
        xComboBox2 = new com.rameses.rcp.control.XComboBox();
        xFormPanel2 = new com.rameses.rcp.control.XFormPanel();
        xButton1 = new com.rameses.rcp.control.XButton();
        xLabel7 = new com.rameses.rcp.control.XLabel();
        xLabel2 = new com.rameses.rcp.control.XLabel();
        xLabel3 = new com.rameses.rcp.control.XLabel();
        xLabel4 = new com.rameses.rcp.control.XLabel();
        xLabel5 = new com.rameses.rcp.control.XLabel();
        xLabel6 = new com.rameses.rcp.control.XLabel();
        xLookupField1 = new com.rameses.rcp.control.XLookupField();
        xLabel8 = new com.rameses.rcp.control.XLabel();
        xLabel9 = new com.rameses.rcp.control.XLabel();
        xIntegerField2 = new com.rameses.rcp.control.XIntegerField();
        xCheckBox1 = new com.rameses.rcp.control.XCheckBox();
        jPanel1 = new javax.swing.JPanel();
        xDataTable1 = new com.rameses.rcp.control.XDataTable();
        xFormPanel3 = new com.rameses.rcp.control.XFormPanel();
        xDecimalField1 = new com.rameses.rcp.control.XDecimalField();
        xDecimalField2 = new com.rameses.rcp.control.XDecimalField();
        jPanel3 = new javax.swing.JPanel();
        xFormPanel4 = new com.rameses.rcp.control.XFormPanel();
        xLabel11 = new com.rameses.rcp.control.XLabel();
        xTextField2 = new com.rameses.rcp.control.XTextField();
        xTextField3 = new com.rameses.rcp.control.XTextField();
        xTextField4 = new com.rameses.rcp.control.XTextField();
        xTextField5 = new com.rameses.rcp.control.XTextField();
        xDateField5 = new com.rameses.rcp.control.XDateField();
        xLabel12 = new com.rameses.rcp.control.XLabel();
        xLabel13 = new com.rameses.rcp.control.XLabel();
        xLabel14 = new com.rameses.rcp.control.XLabel();
        xTextField7 = new com.rameses.rcp.control.XTextField();
        xTextField8 = new com.rameses.rcp.control.XTextField();
        xTextField9 = new com.rameses.rcp.control.XTextField();
        xDateField4 = new com.rameses.rcp.control.XDateField();

        jPanel2.setAutoscrolls(true);

        xFormPanel1.setBorder(null);
        xFormPanel1.setCaptionWidth(120);

        xLabel1.setCaption("State");
        xLabel1.setExpression("#{entity.state}");
        xLabel1.setCellPadding(new java.awt.Insets(0, 0, 10, 0));
        xLabel1.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        xLabel1.setForeground(new java.awt.Color(255, 0, 0));
        xLabel1.setPreferredSize(new java.awt.Dimension(0, 19));
        xFormPanel1.add(xLabel1);

        xComboBox1.setCaption("App Type");
        xComboBox1.setItems("apptypes");
        xComboBox1.setName("entity.apptype"); // NOI18N
        xComboBox1.setPreferredSize(new java.awt.Dimension(100, 20));
        xComboBox1.setRequired(true);
        xFormPanel1.add(xComboBox1);

        xTextField1.setCaption("App No.");
        xTextField1.setName("entity.appno"); // NOI18N
        xFormPanel1.add(xTextField1);

        xIntegerField1.setCaption("App Year");
        xIntegerField1.setName("entity.appyear"); // NOI18N
        xIntegerField1.setRequired(true);
        xFormPanel1.add(xIntegerField1);

        xDateField1.setCaption("Date Applied");
        xDateField1.setName("entity.dtapplied"); // NOI18N
        xDateField1.setRequired(true);
        xFormPanel1.add(xDateField1);

        xDateField2.setCaption("Date Approved");
        xDateField2.setName("entity.dtapproved"); // NOI18N
        xDateField2.setRequired(true);
        xFormPanel1.add(xDateField2);

        xDateField3.setCaption("Expiry Date");
        xDateField3.setName("entity.dtexpiry"); // NOI18N
        xDateField3.setCellPadding(new java.awt.Insets(0, 0, 10, 0));
        xDateField3.setRequired(true);
        xFormPanel1.add(xDateField3);

        xLookupField2.setCaption("Applicant");
        xLookupField2.setExpression("#{item.name}");
        xLookupField2.setHandler("lookupApplicant");
        xLookupField2.setName("entity.applicant"); // NOI18N
        xLookupField2.setPreferredSize(new java.awt.Dimension(0, 20));
        xLookupField2.setRequired(true);
        xFormPanel1.add(xLookupField2);

        xLabel10.setCaption("Address");
        xLabel10.setDepends(new String[] {"entity.applicant"});
        xLabel10.setExpression("#{entity.applicant.address}");
        xLabel10.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 153, 153)));
        xLabel10.setPreferredSize(new java.awt.Dimension(0, 19));
        xFormPanel1.add(xLabel10);

        xComboBox2.setCaption("Relationship");
        xComboBox2.setDepends(new String[] {"entity.applicant"});
        xComboBox2.setExpression("#{item.title}");
        xComboBox2.setItems("relations");
        xComboBox2.setName("entity.relation"); // NOI18N
        xComboBox2.setCellPadding(new java.awt.Insets(0, 0, 10, 0));
        xComboBox2.setPreferredSize(new java.awt.Dimension(0, 20));
        xComboBox2.setRequired(true);
        xFormPanel1.add(xComboBox2);

        xFormPanel2.setOrientation(com.rameses.rcp.constant.UIConstants.HORIZONTAL);
        xFormPanel2.setPadding(new java.awt.Insets(0, 0, 0, 0));
        xFormPanel2.setShowCaption(false);
        xFormPanel2.setStretchWidth(100);

        xButton1.setName("openDeceased"); // NOI18N
        xButton1.setImmediate(true);
        xButton1.setPreferredSize(new java.awt.Dimension(118, 23));
        xButton1.setShowCaption(false);
        xButton1.setText("Deceased Person");
        xFormPanel2.add(xButton1);

        xLabel7.setCaption("Nationality");
        xLabel7.setDepends(new String[] {"entity.deceased"});
        xLabel7.setExpression("#{entity.deceased.name}");
        xLabel7.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 153, 153)));
        xLabel7.setPreferredSize(new java.awt.Dimension(0, 21));
        xLabel7.setShowCaption(false);
        xFormPanel2.add(xLabel7);

        xFormPanel1.add(xFormPanel2);

        xLabel2.setCaption("Nationality");
        xLabel2.setDepends(new String[] {"entity.deceased"});
        xLabel2.setExpression("#{entity.deceased.nationality}");
        xLabel2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 153, 153)));
        xLabel2.setPreferredSize(new java.awt.Dimension(0, 19));
        xFormPanel1.add(xLabel2);

        xLabel3.setCaption("Age");
        xLabel3.setDepends(new String[] {"entity.deceased"});
        xLabel3.setExpression("#{entity.deceased.age}");
        xLabel3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 153, 153)));
        xLabel3.setPreferredSize(new java.awt.Dimension(0, 19));
        xFormPanel1.add(xLabel3);

        xLabel4.setCaption("Sex");
        xLabel4.setDepends(new String[] {"entity.deceased"});
        xLabel4.setExpression("#{entity.deceased.sex}");
        xLabel4.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 153, 153)));
        xLabel4.setPreferredSize(new java.awt.Dimension(0, 19));
        xFormPanel1.add(xLabel4);

        xLabel5.setCaption("Date of Death");
        xLabel5.setDepends(new String[] {"entity.deceased"});
        xLabel5.setExpression("#{entity.deceased.dtdied}");
        xLabel5.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 153, 153)));
        xLabel5.setPreferredSize(new java.awt.Dimension(0, 19));
        xFormPanel1.add(xLabel5);

        xLabel6.setCaption("Cause of Death");
        xLabel6.setDepends(new String[] {"entity.deceased"});
        xLabel6.setExpression("#{entity.deceased.causeofdeath.title}");
        xLabel6.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 153, 153)));
        xLabel6.setCellPadding(new java.awt.Insets(0, 0, 10, 0));
        xLabel6.setPreferredSize(new java.awt.Dimension(0, 19));
        xFormPanel1.add(xLabel6);

        xLookupField1.setCaption("Resource");
        xLookupField1.setExpression("#{item.name}");
        xLookupField1.setHandler("cemetery_resource:lookup");
        xLookupField1.setName("entity.resourceinfo"); // NOI18N
        xLookupField1.setPreferredSize(new java.awt.Dimension(0, 20));
        xLookupField1.setRequired(true);
        xFormPanel1.add(xLookupField1);

        xLabel8.setCaption("Resource Type");
        xLabel8.setDepends(new String[] {"entity.resourceinfo"});
        xLabel8.setExpression("#{entity.resourceinfo.resource.name}");
        xLabel8.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 153, 153)));
        xLabel8.setPreferredSize(new java.awt.Dimension(0, 19));
        xFormPanel1.add(xLabel8);

        xLabel9.setCaption("Area (sqm)");
        xLabel9.setDepends(new String[] {"entity.resourceinfo"});
        xLabel9.setExpression("#{entity.resourceinfo.areasqm}");
        xLabel9.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 153, 153)));
        xLabel9.setPreferredSize(new java.awt.Dimension(0, 19));
        xFormPanel1.add(xLabel9);

        xIntegerField2.setCaption("Lease Duration");
        xIntegerField2.setName("entity.leaseduration"); // NOI18N
        xFormPanel1.add(xIntegerField2);

        xCheckBox1.setCaption("Is Renewable?");
        xCheckBox1.setName("entity.renewable"); // NOI18N
        xFormPanel1.add(xCheckBox1);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 560, Short.MAX_VALUE)
            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel2Layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(xFormPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 540, Short.MAX_VALUE)
                    .addContainerGap()))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 517, Short.MAX_VALUE)
            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel2Layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(xFormPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addContainerGap()))
        );

        jTabbedPane1.addTab("Application", jPanel2);

        xDataTable1.setHandler("itemHandlers.fees");
        xDataTable1.setColumns(new com.rameses.rcp.common.Column[]{
            new com.rameses.rcp.common.Column(new Object[]{
                new Object[]{"name", "item.title"}
                , new Object[]{"caption", "Account"}
                , new Object[]{"width", 100}
                , new Object[]{"minWidth", 200}
                , new Object[]{"maxWidth", 0}
                , new Object[]{"required", false}
                , new Object[]{"resizable", true}
                , new Object[]{"nullWhenEmpty", true}
                , new Object[]{"editable", false}
                , new Object[]{"visible", true}
                , new Object[]{"visibleWhen", null}
                , new Object[]{"textCase", com.rameses.rcp.constant.TextCase.NONE}
                , new Object[]{"typeHandler", new com.rameses.rcp.common.TextColumnHandler()}
            }),
            new com.rameses.rcp.common.Column(new Object[]{
                new Object[]{"name", "amount"}
                , new Object[]{"caption", "Amount"}
                , new Object[]{"width", 100}
                , new Object[]{"minWidth", 0}
                , new Object[]{"maxWidth", 0}
                , new Object[]{"required", false}
                , new Object[]{"resizable", true}
                , new Object[]{"nullWhenEmpty", true}
                , new Object[]{"editable", false}
                , new Object[]{"visible", true}
                , new Object[]{"visibleWhen", null}
                , new Object[]{"textCase", com.rameses.rcp.constant.TextCase.NONE}
                , new Object[]{"typeHandler", new com.rameses.rcp.common.DecimalColumnHandler("#,##0.00", -1.0, -1.0, false, 2)}
            }),
            new com.rameses.rcp.common.Column(new Object[]{
                new Object[]{"name", "amtpaid"}
                , new Object[]{"caption", "Payment Made"}
                , new Object[]{"width", 100}
                , new Object[]{"minWidth", 0}
                , new Object[]{"maxWidth", 0}
                , new Object[]{"required", false}
                , new Object[]{"resizable", true}
                , new Object[]{"nullWhenEmpty", true}
                , new Object[]{"editable", false}
                , new Object[]{"visible", true}
                , new Object[]{"visibleWhen", null}
                , new Object[]{"textCase", com.rameses.rcp.constant.TextCase.NONE}
                , new Object[]{"typeHandler", new com.rameses.rcp.common.DecimalColumnHandler("#,##0.00", -1.0, -1.0, false, 2)}
            })
        });

        xFormPanel3.setOrientation(com.rameses.rcp.constant.UIConstants.HORIZONTAL);

        xDecimalField1.setCaption("Total");
        xDecimalField1.setName("amount"); // NOI18N
        xFormPanel3.add(xDecimalField1);

        xDecimalField2.setCaption("Amount Paid");
        xDecimalField2.setName("amtpaid"); // NOI18N
        xDecimalField2.setCellPadding(new java.awt.Insets(0, 20, 0, 0));
        xFormPanel3.add(xDecimalField2);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(xDataTable1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGap(0, 148, Short.MAX_VALUE)
                        .addComponent(xFormPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(xDataTable1, javax.swing.GroupLayout.DEFAULT_SIZE, 456, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(xFormPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        jTabbedPane1.addTab("Assessment", jPanel1);

        xLabel11.setExpression("#{\"LESSOR\"}");
        xLabel11.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        xLabel11.setShowCaption(false);
        xFormPanel4.add(xLabel11);

        xTextField2.setCaption("Mayor Name");
        xTextField2.setName("entity.lessor.name"); // NOI18N
        xTextField2.setCaptionWidth(120);
        xTextField2.setCellPadding(new java.awt.Insets(10, 20, 0, 0));
        xTextField2.setPreferredSize(new java.awt.Dimension(0, 20));
        xTextField2.setRequired(true);
        xFormPanel4.add(xTextField2);

        xTextField3.setCaption("Mayor Title");
        xTextField3.setName("entity.lessor.title"); // NOI18N
        xTextField3.setCaptionWidth(120);
        xTextField3.setCellPadding(new java.awt.Insets(0, 20, 0, 0));
        xTextField3.setPreferredSize(new java.awt.Dimension(0, 20));
        xTextField3.setRequired(true);
        xFormPanel4.add(xTextField3);

        xTextField4.setCaption("CTC No.");
        xTextField4.setName("entity.lessor.ctcno"); // NOI18N
        xTextField4.setCaptionWidth(120);
        xTextField4.setCellPadding(new java.awt.Insets(0, 20, 0, 0));
        xTextField4.setPreferredSize(new java.awt.Dimension(0, 20));
        xTextField4.setRequired(true);
        xFormPanel4.add(xTextField4);

        xTextField5.setCaption("Place Issued");
        xTextField5.setName("entity.lessor.ctcplaceissued"); // NOI18N
        xTextField5.setCaptionWidth(120);
        xTextField5.setCellPadding(new java.awt.Insets(0, 20, 0, 0));
        xTextField5.setPreferredSize(new java.awt.Dimension(0, 20));
        xTextField5.setRequired(true);
        xFormPanel4.add(xTextField5);

        xDateField5.setCaption("Date Issued");
        xDateField5.setName("entity.lessor.ctcdtissued"); // NOI18N
        xDateField5.setCaptionWidth(120);
        xDateField5.setCellPadding(new java.awt.Insets(0, 20, 0, 0));
        xDateField5.setRequired(true);
        xFormPanel4.add(xDateField5);

        xLabel12.setExpression("#{\"LESSEE\"}");
        xLabel12.setCellPadding(new java.awt.Insets(15, 0, 0, 0));
        xLabel12.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        xLabel12.setShowCaption(false);
        xFormPanel4.add(xLabel12);

        xLabel13.setCaption("Applicant Name");
        xLabel13.setDepends(new String[] {"entity.applicant"});
        xLabel13.setExpression("#{entity.applicant.name}");
        xLabel13.setCaptionWidth(120);
        xLabel13.setCellPadding(new java.awt.Insets(10, 20, 0, 0));
        xLabel13.setPreferredSize(new java.awt.Dimension(0, 19));
        xFormPanel4.add(xLabel13);

        xLabel14.setCaption("Applicant Address");
        xLabel14.setDepends(new String[] {"entity.applicant"});
        xLabel14.setExpression("#{entity.applicant.address}");
        xLabel14.setCaptionWidth(120);
        xLabel14.setCellPadding(new java.awt.Insets(0, 20, 0, 0));
        xLabel14.setPreferredSize(new java.awt.Dimension(0, 19));
        xFormPanel4.add(xLabel14);

        xTextField7.setCaption("CTC No.");
        xTextField7.setName("entity.lessee.ctcno"); // NOI18N
        xTextField7.setCaptionWidth(120);
        xTextField7.setCellPadding(new java.awt.Insets(0, 20, 0, 0));
        xTextField7.setPreferredSize(new java.awt.Dimension(0, 20));
        xTextField7.setRequired(true);
        xFormPanel4.add(xTextField7);

        xTextField8.setCaption("Place Issued");
        xTextField8.setName("entity.lessee.ctcplaceissued"); // NOI18N
        xTextField8.setCaptionWidth(120);
        xTextField8.setCellPadding(new java.awt.Insets(0, 20, 0, 0));
        xTextField8.setPreferredSize(new java.awt.Dimension(0, 20));
        xTextField8.setRequired(true);
        xFormPanel4.add(xTextField8);

        xTextField9.setCaption("Date Issued");
        xTextField9.setName("entity.lessee.ctcdtissued"); // NOI18N
        xTextField9.setCaptionWidth(120);
        xTextField9.setCellPadding(new java.awt.Insets(0, 20, 0, 0));
        xTextField9.setPreferredSize(new java.awt.Dimension(0, 20));
        xTextField9.setRequired(true);
        xFormPanel4.add(xTextField9);

        xDateField4.setCaption("Date Issued");
        xDateField4.setName("entity.lessee.ctcdtissued"); // NOI18N
        xDateField4.setCaptionWidth(120);
        xDateField4.setCellPadding(new java.awt.Insets(0, 20, 0, 0));
        xDateField4.setRequired(true);
        xFormPanel4.add(xDateField4);

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(xFormPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, 359, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(191, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(xFormPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, 349, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(157, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Signatories", jPanel3);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 565, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(54, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jTabbedPane1)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JTabbedPane jTabbedPane1;
    private com.rameses.rcp.control.XButton xButton1;
    private com.rameses.rcp.control.XCheckBox xCheckBox1;
    private com.rameses.rcp.control.XComboBox xComboBox1;
    private com.rameses.rcp.control.XComboBox xComboBox2;
    private com.rameses.rcp.control.XDataTable xDataTable1;
    private com.rameses.rcp.control.XDateField xDateField1;
    private com.rameses.rcp.control.XDateField xDateField2;
    private com.rameses.rcp.control.XDateField xDateField3;
    private com.rameses.rcp.control.XDateField xDateField4;
    private com.rameses.rcp.control.XDateField xDateField5;
    private com.rameses.rcp.control.XDecimalField xDecimalField1;
    private com.rameses.rcp.control.XDecimalField xDecimalField2;
    private com.rameses.rcp.control.XFormPanel xFormPanel1;
    private com.rameses.rcp.control.XFormPanel xFormPanel2;
    private com.rameses.rcp.control.XFormPanel xFormPanel3;
    private com.rameses.rcp.control.XFormPanel xFormPanel4;
    private com.rameses.rcp.control.XIntegerField xIntegerField1;
    private com.rameses.rcp.control.XIntegerField xIntegerField2;
    private com.rameses.rcp.control.XLabel xLabel1;
    private com.rameses.rcp.control.XLabel xLabel10;
    private com.rameses.rcp.control.XLabel xLabel11;
    private com.rameses.rcp.control.XLabel xLabel12;
    private com.rameses.rcp.control.XLabel xLabel13;
    private com.rameses.rcp.control.XLabel xLabel14;
    private com.rameses.rcp.control.XLabel xLabel2;
    private com.rameses.rcp.control.XLabel xLabel3;
    private com.rameses.rcp.control.XLabel xLabel4;
    private com.rameses.rcp.control.XLabel xLabel5;
    private com.rameses.rcp.control.XLabel xLabel6;
    private com.rameses.rcp.control.XLabel xLabel7;
    private com.rameses.rcp.control.XLabel xLabel8;
    private com.rameses.rcp.control.XLabel xLabel9;
    private com.rameses.rcp.control.XLookupField xLookupField1;
    private com.rameses.rcp.control.XLookupField xLookupField2;
    private com.rameses.rcp.control.XTextField xTextField1;
    private com.rameses.rcp.control.XTextField xTextField2;
    private com.rameses.rcp.control.XTextField xTextField3;
    private com.rameses.rcp.control.XTextField xTextField4;
    private com.rameses.rcp.control.XTextField xTextField5;
    private com.rameses.rcp.control.XTextField xTextField7;
    private com.rameses.rcp.control.XTextField xTextField8;
    private com.rameses.rcp.control.XTextField xTextField9;
    // End of variables declaration//GEN-END:variables
}
