/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package comis.views;

import com.rameses.rcp.ui.annotations.StyleSheet;
import com.rameses.rcp.ui.annotations.Template;
import com.rameses.seti2.views.WorkflowTaskFormPage;

@Template(WorkflowTaskFormPage.class)
@StyleSheet()
public class ApplicationNewPage extends javax.swing.JPanel {

    /**
     * Creates new form ResourcePage
     */
    public ApplicationNewPage() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        xFormPanel1 = new com.rameses.rcp.control.XFormPanel();
        xLookupField2 = new com.rameses.rcp.control.XLookupField();
        xLabel10 = new com.rameses.rcp.control.XLabel();
        xComboBox2 = new com.rameses.rcp.control.XComboBox();
        xFormPanel2 = new com.rameses.rcp.control.XFormPanel();
        xButton1 = new com.rameses.rcp.control.XButton();
        xLabel7 = new com.rameses.rcp.control.XLabel();
        xLabel2 = new com.rameses.rcp.control.XLabel();
        xLabel3 = new com.rameses.rcp.control.XLabel();
        xLabel4 = new com.rameses.rcp.control.XLabel();
        xLabel5 = new com.rameses.rcp.control.XLabel();
        xLabel6 = new com.rameses.rcp.control.XLabel();
        xLookupField1 = new com.rameses.rcp.control.XLookupField();
        xLabel8 = new com.rameses.rcp.control.XLabel();
        xLabel9 = new com.rameses.rcp.control.XLabel();
        xIntegerField2 = new com.rameses.rcp.control.XIntegerField();
        xCheckBox1 = new com.rameses.rcp.control.XCheckBox();

        jPanel2.setAutoscrolls(true);

        xFormPanel1.setBorder(null);
        xFormPanel1.setCaptionWidth(120);

        xLookupField2.setCaption("Applicant");
        xLookupField2.setExpression("#{item.name}");
        xLookupField2.setHandler("lookupApplicant");
        xLookupField2.setName("entity.applicant"); // NOI18N
        xLookupField2.setPreferredSize(new java.awt.Dimension(0, 20));
        xLookupField2.setRequired(true);
        xFormPanel1.add(xLookupField2);

        xLabel10.setCaption("Address");
        xLabel10.setDepends(new String[] {"entity.applicant"});
        xLabel10.setExpression("#{entity.applicant.address}");
        xLabel10.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 153, 153)));
        xLabel10.setPreferredSize(new java.awt.Dimension(0, 19));
        xFormPanel1.add(xLabel10);

        xComboBox2.setCaption("Relationship");
        xComboBox2.setDepends(new String[] {"entity.applicant"});
        xComboBox2.setExpression("#{item.title}");
        xComboBox2.setItems("relations");
        xComboBox2.setName("entity.relation"); // NOI18N
        xComboBox2.setCellPadding(new java.awt.Insets(0, 0, 10, 0));
        xComboBox2.setPreferredSize(new java.awt.Dimension(0, 20));
        xComboBox2.setRequired(true);
        xFormPanel1.add(xComboBox2);

        xFormPanel2.setOrientation(com.rameses.rcp.constant.UIConstants.HORIZONTAL);
        xFormPanel2.setPadding(new java.awt.Insets(0, 0, 0, 0));
        xFormPanel2.setShowCaption(false);
        xFormPanel2.setStretchWidth(100);

        xButton1.setName("openDeceased"); // NOI18N
        xButton1.setImmediate(true);
        xButton1.setPreferredSize(new java.awt.Dimension(118, 23));
        xButton1.setShowCaption(false);
        xButton1.setText("Deceased Person");
        xFormPanel2.add(xButton1);

        xLabel7.setCaption("Nationality");
        xLabel7.setDepends(new String[] {"entity.deceased"});
        xLabel7.setExpression("#{entity.deceased.name}");
        xLabel7.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 153, 153)));
        xLabel7.setPreferredSize(new java.awt.Dimension(0, 21));
        xLabel7.setShowCaption(false);
        xFormPanel2.add(xLabel7);

        xFormPanel1.add(xFormPanel2);

        xLabel2.setCaption("Nationality");
        xLabel2.setDepends(new String[] {"entity.deceased"});
        xLabel2.setExpression("#{entity.deceased.nationality}");
        xLabel2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 153, 153)));
        xLabel2.setPreferredSize(new java.awt.Dimension(0, 19));
        xFormPanel1.add(xLabel2);

        xLabel3.setCaption("Age");
        xLabel3.setDepends(new String[] {"entity.deceased"});
        xLabel3.setExpression("#{entity.deceased.age}");
        xLabel3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 153, 153)));
        xLabel3.setPreferredSize(new java.awt.Dimension(0, 19));
        xFormPanel1.add(xLabel3);

        xLabel4.setCaption("Sex");
        xLabel4.setDepends(new String[] {"entity.deceased"});
        xLabel4.setExpression("#{entity.deceased.sex}");
        xLabel4.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 153, 153)));
        xLabel4.setPreferredSize(new java.awt.Dimension(0, 19));
        xFormPanel1.add(xLabel4);

        xLabel5.setCaption("Date of Death");
        xLabel5.setDepends(new String[] {"entity.deceased"});
        xLabel5.setExpression("#{entity.deceased.dtdied}");
        xLabel5.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 153, 153)));
        xLabel5.setPreferredSize(new java.awt.Dimension(0, 19));
        xFormPanel1.add(xLabel5);

        xLabel6.setCaption("Cause of Death");
        xLabel6.setDepends(new String[] {"entity.deceased"});
        xLabel6.setExpression("#{entity.deceased.causeofdeath.title}");
        xLabel6.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 153, 153)));
        xLabel6.setCellPadding(new java.awt.Insets(0, 0, 10, 0));
        xLabel6.setPreferredSize(new java.awt.Dimension(0, 19));
        xFormPanel1.add(xLabel6);

        xLookupField1.setCaption("Resource");
        xLookupField1.setExpression("#{item.name}");
        xLookupField1.setHandler("cemetery_resource:lookup");
        xLookupField1.setName("entity.resourceinfo"); // NOI18N
        xLookupField1.setPreferredSize(new java.awt.Dimension(0, 20));
        xLookupField1.setRequired(true);
        xFormPanel1.add(xLookupField1);

        xLabel8.setCaption("Resource Type");
        xLabel8.setDepends(new String[] {"entity.resourceinfo"});
        xLabel8.setExpression("#{entity.resourceinfo.resource.name}");
        xLabel8.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 153, 153)));
        xLabel8.setPreferredSize(new java.awt.Dimension(0, 19));
        xFormPanel1.add(xLabel8);

        xLabel9.setCaption("Area (sqm)");
        xLabel9.setDepends(new String[] {"entity.resourceinfo"});
        xLabel9.setExpression("#{entity.resourceinfo.areasqm}");
        xLabel9.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 153, 153)));
        xLabel9.setPreferredSize(new java.awt.Dimension(0, 19));
        xFormPanel1.add(xLabel9);

        xIntegerField2.setCaption("Lease Duration");
        xIntegerField2.setName("entity.leaseduration"); // NOI18N
        xFormPanel1.add(xIntegerField2);

        xCheckBox1.setCaption("Is Renewable?");
        xCheckBox1.setName("entity.renewable"); // NOI18N
        xFormPanel1.add(xCheckBox1);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(xFormPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 540, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(xFormPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 377, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(27, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel jPanel2;
    private com.rameses.rcp.control.XButton xButton1;
    private com.rameses.rcp.control.XCheckBox xCheckBox1;
    private com.rameses.rcp.control.XComboBox xComboBox2;
    private com.rameses.rcp.control.XFormPanel xFormPanel1;
    private com.rameses.rcp.control.XFormPanel xFormPanel2;
    private com.rameses.rcp.control.XIntegerField xIntegerField2;
    private com.rameses.rcp.control.XLabel xLabel10;
    private com.rameses.rcp.control.XLabel xLabel2;
    private com.rameses.rcp.control.XLabel xLabel3;
    private com.rameses.rcp.control.XLabel xLabel4;
    private com.rameses.rcp.control.XLabel xLabel5;
    private com.rameses.rcp.control.XLabel xLabel6;
    private com.rameses.rcp.control.XLabel xLabel7;
    private com.rameses.rcp.control.XLabel xLabel8;
    private com.rameses.rcp.control.XLabel xLabel9;
    private com.rameses.rcp.control.XLookupField xLookupField1;
    private com.rameses.rcp.control.XLookupField xLookupField2;
    // End of variables declaration//GEN-END:variables
}
