/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package comis.views;

import com.rameses.rcp.ui.annotations.Template;
import com.rameses.seti2.views.CrudFormPage;

@Template(CrudFormPage.class)
public class DeceasedPage extends javax.swing.JPanel {

    /**
     * Creates new form ResourcePage
     */
    public DeceasedPage() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        xFormPanel1 = new com.rameses.rcp.control.XFormPanel();
        xTextField1 = new com.rameses.rcp.control.XTextField();
        xComboBox1 = new com.rameses.rcp.control.XComboBox();
        xFormPanel2 = new com.rameses.rcp.control.XFormPanel();
        xIntegerField1 = new com.rameses.rcp.control.XIntegerField();
        xComboBox5 = new com.rameses.rcp.control.XComboBox();
        xComboBox2 = new com.rameses.rcp.control.XComboBox();
        xDateField1 = new com.rameses.rcp.control.XDateField();
        xComboBox3 = new com.rameses.rcp.control.XComboBox();
        xComboBox4 = new com.rameses.rcp.control.XComboBox();
        xLabel2 = new com.rameses.rcp.control.XLabel();
        xTextField3 = new com.rameses.rcp.control.XTextField();
        xTextField4 = new com.rameses.rcp.control.XTextField();
        xTextField5 = new com.rameses.rcp.control.XTextField();

        xFormPanel1.setCaptionWidth(130);

        xTextField1.setCaption("Name");
        xTextField1.setName("entity.name"); // NOI18N
        xTextField1.setPreferredSize(new java.awt.Dimension(0, 20));
        xTextField1.setRequired(true);
        xFormPanel1.add(xTextField1);

        xComboBox1.setCaption("Nationality");
        xComboBox1.setItems("nationalities");
        xComboBox1.setName("entity.nationality"); // NOI18N
        xComboBox1.setPreferredSize(new java.awt.Dimension(0, 20));
        xComboBox1.setRequired(true);
        xFormPanel1.add(xComboBox1);

        xFormPanel2.setCaptionBorder(null);
        xFormPanel2.setCaptionWidth(130);
        xFormPanel2.setOrientation(com.rameses.rcp.constant.UIConstants.HORIZONTAL);
        xFormPanel2.setPadding(new java.awt.Insets(0, 0, 0, 0));
        xFormPanel2.setShowCaption(false);

        xIntegerField1.setCaption("Age");
        xIntegerField1.setName("entity.age"); // NOI18N
        xIntegerField1.setPreferredSize(new java.awt.Dimension(50, 20));
        xIntegerField1.setRequired(true);
        xFormPanel2.add(xIntegerField1);

        xComboBox5.setItems("agetypes");
        xComboBox5.setName("entity.agetype"); // NOI18N
        xComboBox5.setPreferredSize(new java.awt.Dimension(98, 20));
        xComboBox5.setShowCaption(false);
        xFormPanel2.add(xComboBox5);

        xFormPanel1.add(xFormPanel2);

        xComboBox2.setCaption("Sex");
        xComboBox2.setItems("sexes");
        xComboBox2.setName("entity.sex"); // NOI18N
        xComboBox2.setPreferredSize(new java.awt.Dimension(150, 20));
        xComboBox2.setRequired(true);
        xFormPanel1.add(xComboBox2);

        xDateField1.setCaption("Date of Death");
        xDateField1.setName("entity.dtdied"); // NOI18N
        xDateField1.setCellPadding(new java.awt.Insets(0, 0, 20, 0));
        xDateField1.setPreferredSize(new java.awt.Dimension(150, 20));
        xDateField1.setRequired(true);
        xFormPanel1.add(xDateField1);

        xComboBox3.setCaption("Cause of Death");
        xComboBox3.setExpression("#{item.title}");
        xComboBox3.setItems("causeofdeaths");
        xComboBox3.setName("entity.causeofdeath"); // NOI18N
        xComboBox3.setPreferredSize(new java.awt.Dimension(0, 20));
        xComboBox3.setRequired(true);
        xFormPanel1.add(xComboBox3);

        xComboBox4.setCaption("Permission Type");
        xComboBox4.setItems("permissiontypes");
        xComboBox4.setName("entity.permissiontype"); // NOI18N
        xComboBox4.setPreferredSize(new java.awt.Dimension(0, 20));
        xComboBox4.setRequired(true);
        xFormPanel1.add(xComboBox4);

        xLabel2.setExpression("#{\"In case of disinterment\"}");
        xLabel2.setCellPadding(new java.awt.Insets(5, 0, 0, 0));
        xLabel2.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        xLabel2.setPreferredSize(new java.awt.Dimension(0, 19));
        xLabel2.setShowCaption(false);
        xFormPanel1.add(xLabel2);

        xTextField3.setCaption("Infectious or Non-Infections");
        xTextField3.setDepends(new String[] {"entity.permissiontype"});
        xTextField3.setName("entity.infections"); // NOI18N
        xTextField3.setCaptionWidth(190);
        xTextField3.setCellPadding(new java.awt.Insets(5, 30, 0, 0));
        xTextField3.setPreferredSize(new java.awt.Dimension(0, 20));
        xFormPanel1.add(xTextField3);

        xTextField4.setCaption("Body embalmed or not embalmed");
        xTextField4.setDepends(new String[] {"entity.permissiontype"});
        xTextField4.setName("entity.embalmed"); // NOI18N
        xTextField4.setCaptionWidth(190);
        xTextField4.setCellPadding(new java.awt.Insets(0, 30, 0, 0));
        xTextField4.setPreferredSize(new java.awt.Dimension(0, 20));
        xFormPanel1.add(xTextField4);

        xTextField5.setCaption("Disposition of remains");
        xTextField5.setDepends(new String[] {"entity.permissiontype"});
        xTextField5.setName("entity.disposition"); // NOI18N
        xTextField5.setCaptionWidth(190);
        xTextField5.setCellPadding(new java.awt.Insets(0, 30, 0, 0));
        xTextField5.setPreferredSize(new java.awt.Dimension(0, 20));
        xFormPanel1.add(xTextField5);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(xFormPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 492, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(xFormPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 329, Short.MAX_VALUE)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private com.rameses.rcp.control.XComboBox xComboBox1;
    private com.rameses.rcp.control.XComboBox xComboBox2;
    private com.rameses.rcp.control.XComboBox xComboBox3;
    private com.rameses.rcp.control.XComboBox xComboBox4;
    private com.rameses.rcp.control.XComboBox xComboBox5;
    private com.rameses.rcp.control.XDateField xDateField1;
    private com.rameses.rcp.control.XFormPanel xFormPanel1;
    private com.rameses.rcp.control.XFormPanel xFormPanel2;
    private com.rameses.rcp.control.XIntegerField xIntegerField1;
    private com.rameses.rcp.control.XLabel xLabel2;
    private com.rameses.rcp.control.XTextField xTextField1;
    private com.rameses.rcp.control.XTextField xTextField3;
    private com.rameses.rcp.control.XTextField xTextField4;
    private com.rameses.rcp.control.XTextField xTextField5;
    // End of variables declaration//GEN-END:variables
}
